version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db_transversal
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transversal_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  model:
    build:
      context: ./model
    container_name: model_transversal
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transversal_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  controller:
    build:
      context: ./controller
    container_name: controller_transversal
    ports:
      - "4000:4000"
    volumes:
      - ./controller/src:/app/src
    depends_on:
      - model

  view:
    build:
      context: ./view
    container_name: view_transversal
    ports:
      - "5173:5173"
    volumes:
      - ./view/src:/app/src
    depends_on:
      - controller

volumes:
  postgres_data:
